version: '3'
services:
  nuoyis-lnmp:
    container_name: nuoyis-lnmp
    image: nuoyis-lnmp-np:l
    networks: 
      nuoyis-net:
        aliases:
          - nuoyis-lnmp
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      # nginx 配置文件
      - /nuoyis-server/web/nginx/conf:/nuoyis-web/nginx/conf
      # nginx 网站目录
      - /nuoyis-server/web/nginx/webside:/nuoyis-web/nginx/webside
      # nginx ssl
      - /nuoyis-server/web/nginx/ssl:/nuoyis-web/nginx/ssl
      # Log 目录
      - /var/log:/nuoyis-web/logs
      # mariadb 数据与配置
      - /nuoyis-server/web/mariadb/init:/docker-entrypoint-initdb.d
      # MariaDB 数据目录
      - /nuoyis-server/web/mariadb/server:/nuoyis-web/mariadb/data
      # MariaDB 导入目录（自动导入）
      - /nuoyis-server/web/mariadb/import:/nuoyis-web/mariadb/import
      # MariaDB 配置
      - /nuoyis-server/web/mariadb/config:/nuoyis-web/mariadb/config
    environment:
      TIME_ZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "epLpvLcSj9c0U2Vi"
    shm_size: '1g'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    user: "${SUID}:${SGID}"
    restart: always

networks:
  nuoyis-net:
    name: nuoyis-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.223.0/24
          gateway: 192.168.223.1

