name: autobuild latest Docker Images

on:
  workflow_dispatch:    # 可手动触发
  repository_dispatch:
    types: [autobuild]
  
permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lnmp-np-build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      
      - name: lnmp-np config
        run: |
          mkdir -p build/{config,software}
          cp -r lnmp-np/config/* build/config
          cp -r software/* build/software
          cp -r config/* build/config
          cp -r Dockerfile build/
      
      - name: lnmp docker build
        run: |
          docker build --compress --squash --no-cache --build-arg BUILD_TYPE=lnmp-np -t nuoyis1024/lnmp-np:${{ matrix.arch }} build

      - name: Run container
        run: |
          docker run -d --name lnmp-np-test -p 8080:80 nuoyis1024/lnmp-np:${{ matrix.arch }}
          sleep 10
          docker logs lnmp-np-test
          docker images

      - name: Run CI test
        run: docker exec lnmp-np-test /web/healthcheck.sh

      - name: Log in to dockerhub and aliyun dockerhub
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: lnmp-np docker push
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker push nuoyis1024/lnmp-np:${{ matrix.arch }}
            docker tag nuoyis1024/lnmp-np:${{ matrix.arch }} registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:${{ matrix.arch }}
            docker push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:${{ matrix.arch }}

  lnmp-build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    needs: [lnmp-np-build]
    steps:
      - uses: actions/checkout@v4
      
      - name: lnmp config
        run: |
          mkdir -p build/{config,software}
          cp -r lnmp/config/* build/config
          cp -r software/* build/software
          cp -r config/* build/config
          cp -r Dockerfile build/
      
      - name: lnmp docker build
        run: |
          docker build --no-cache --build-arg BUILD_TYPE=lnmp -t nuoyis1024/lnmp:${{ matrix.arch }} build

      - name: Run container
        run: |
          docker run -d --name lnmp-test -p 8081:80 nuoyis1024/lnmp:${{ matrix.arch }}
          sleep 10
          docker logs lnmp-test

      - name: Run CI test
        run: docker exec lnmp-test /web/healthcheck.sh

      - name: Log in to dockerhub and aliyun dockerhub
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: lnmp docker push
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker push nuoyis1024/lnmp:${{ matrix.arch }}
            docker tag nuoyis1024/lnmp:${{ matrix.arch }} registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:${{ matrix.arch }}
            docker push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:${{ matrix.arch }}

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [lnmp-np-build,lnmp-build]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to dockerhub and aliyun dockerhub
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Create & Push Multi-arch Manifest
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker manifest create nuoyis1024/lnmp-np:latest \
              --amend nuoyis1024/lnmp-np:amd64 \
              --amend nuoyis1024/lnmp-np:arm64
            docker manifest push nuoyis1024/lnmp-np:latest
            docker manifest create registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:latest \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:amd64 \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:arm64
            docker manifest push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:latest
            docker manifest create nuoyis1024/lnmp:latest \
              --amend nuoyis1024/lnmp:amd64 \
              --amend nuoyis1024/lnmp:arm64
            docker manifest push nuoyis1024/lnmp:latest
            docker manifest create registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:latest \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:amd64 \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:arm64
            docker manifest push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:latest