name: Auto Build on Version Update

on:
  repository_dispatch:
    types: [autobuild-trigger]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build amd64
        run: |
          docker build --no-cache -t nuoyis1024/nuoyis-lnmp:autobuild-amd64 .
          docker push nuoyis1024/nuoyis-lnmp:autobuild-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build arm64
        run: |
          docker build --no-cache -t nuoyis1024/nuoyis-lnmp:autobuild-arm64 .
          docker push nuoyis1024/nuoyis-lnmp:autobuild-arm64

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push Multi-arch Manifest
        run: |
          docker manifest create nuoyis1024/nuoyis-lnmp:autobuild \
            --amend nuoyis1024/nuoyis-lnmp:autobuild-amd64 \
            --amend nuoyis1024/nuoyis-lnmp:autobuild-arm64

          docker manifest push nuoyis1024/nuoyis-lnmp:autobuild