name: Build ARM64
on:
  workflow_dispatch:   # 允许手动触发
  
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: nuoyis1024/nuoyis-lnmp:dev-arm64

      - name: Merge multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t nuoyis1024/nuoyis-lnmp:dev \
            nuoyis1024/nuoyis-lnmp:dev-amd64 \
            nuoyis1024/nuoyis-lnmp:dev-arm64
