name: Build Multi-Arch Image (dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'start.sh'
      - 'dockerfile'
      - 'config/**'
      - 'software/**'
      - '.github/workflows/**'

jobs:
  # 1️⃣ 构建 amd64
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: nuoyis1024/nuoyis-lnmp:dev-amd64

  # 2️⃣ 构建 arm64，依赖 amd64
  build-arm64:
    needs: build-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: nuoyis1024/nuoyis-lnmp:dev-arm64

      - name: Merge multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t nuoyis1024/nuoyis-lnmp:dev \
            nuoyis1024/nuoyis-lnmp:dev-amd64 \
            nuoyis1024/nuoyis-lnmp:dev-arm64