name: Build Multi-Arch Image (dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'start.sh'
      - 'dockerfile'
      - 'config/**'
      - 'software/**'
      - '.github/workflows/**'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build amd64
        run: |
          docker build --no-cache -t nuoyis1024/nuoyis-lnmp:dev-amd64 .
          docker push nuoyis1024/nuoyis-lnmp:dev-amd64

  build-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build arm64
        run: |
          docker build --no-cache -t nuoyis1024/nuoyis-lnmp:dev-arm64 .
          docker push nuoyis1024/nuoyis-lnmp:dev-arm64

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push Multi-arch Manifest
        run: |
          docker manifest create nuoyis1024/nuoyis-lnmp:dev \
            --amend nuoyis1024/nuoyis-lnmp:dev-amd64 \
            --amend nuoyis1024/nuoyis-lnmp:dev-arm64

          docker manifest push nuoyis1024/nuoyis-lnmp:dev