name: Build AMD64 Image

on:
  push:
    branches:
      - dev
    paths:
      - 'start.sh'
      - 'dockerfile'
      - 'config/**'
      - 'software/**'
      - '.github/workflows/**'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t nuoyis1024/nuoyis-lnmp:dev-amd64 \
            --push .

      - name: Trigger arm64 workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: dev-build-arm64.yaml
          repo: ${{ github.repository }}
          ref: dev
          token: ${{ secrets.MY_PAT_TOKEN }}