name: lnmp-Build Multi-Arch Image (dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'start.sh'
      - 'Dockerfile'
      - 'config/**'
      - 'software/**'
      - '.github/workflows/**'
      - 'lnmp-np/**'
      - 'lnmp/**'
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lnmp-builds:
    strategy:
      matrix:
        build_type: [lnmp-np, lnmp]
        arch: [amd64, arm64]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      
      - name: lnmp config
        run: |
          mkdir -p build/{config,software}
          cp -r ${{ matrix.build_type }}/config/* build/config
          cp -r software/* build/software
          cp -r config/* build/config
          cp -r Dockerfile build/
      
      - name: lnmp docker build
        run: |
          docker build --compress --squash --no-cache --build-arg BUILD_TYPE=${{ matrix.build_type }} -t nuoyis1024/${{ matrix.build_type }}:${{ matrix.arch }} build

      - name: Run container
        run: |
          docker run -d --name ${{ matrix.build_type }}-test -p 8080:80 nuoyis1024/${{ matrix.build_type }}:${{ matrix.arch }}
          sleep 10
          docker logs ${{ matrix.build_type }}-test

      - name: Run CI test
        run: docker exec ${{ matrix.build_type }}-test /web/healthcheck.sh

      - name: Log in to dockerhub and aliyun dockerhub
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: lnmp docker push
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker push nuoyis1024/${{ matrix.build_type }}:dev-${{ matrix.arch }}
            docker tag nuoyis1024/${{ matrix.build_type }}:dev-${{ matrix.arch }} registry.cn-hangzhou.aliyuncs.com/nuoyis/${{ matrix.build_type }}:dev-${{ matrix.arch }}
            docker push registry.cn-hangzhou.aliyuncs.com/nuoyis/${{ matrix.build_type }}:dev-${{ matrix.arch }}

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [lnmp-builds]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to dockerhub and aliyun dockerhub
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Create & Push Multi-arch Manifest
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker manifest create nuoyis1024/lnmp-np:dev \
              --amend nuoyis1024/lnmp-np:dev-amd64 \
              --amend nuoyis1024/lnmp-np:dev-arm64
            docker manifest push nuoyis1024/lnmp-np:dev
            docker manifest create registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-amd64 \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-arm64
            docker manifest push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev
            docker manifest create nuoyis1024/lnmp:dev \
              --amend nuoyis1024/lnmp:dev-amd64 \
              --amend nuoyis1024/lnmp:dev-arm64
            docker manifest push nuoyis1024/lnmp:dev
            docker manifest create registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:dev \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:dev-amd64 \
              --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:dev-arm64
            docker manifest push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp:dev