name: lnmp-np-Build Multi-Arch Image (dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'start.sh'
      - 'Dockerfile'
      - 'config/**'
      - 'software/**'
      - '.github/workflows/**'
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lnmp-np-build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to aliyunHub
        run: docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: lnmp-np config
        run: |
          mkdir -p build/{config,software}
          cp -r lnmp-np/config/* build/config
          cp -r software/* build/software
          cp -r config/* build/config
          cp -r Dockerfile build/
      
      - name: lnmp docker build
        run: |
          cd build
          docker build --no-cache --build-arg BUILD_TYPE=lnmp-np -t nuoyis1024/lnmp-np:dev-${{ matrix.arch }} .

      - name: Run container
        run: docker run -d --name lnmp-test -p 8080:80 nuoyis1024/lnmp-np:dev-${{ matrix.arch }}

      - name: Run CI test
        run: docker exec lnmp-test /web/ci-test.sh

      - name: lnmp docker push
        run: |
          docker push nuoyis1024/lnmp-np:dev-${{ matrix.arch }}
          docker tag nuoyis1024/lnmp-np:dev-${{ matrix.arch }} registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-${{ matrix.arch }}
          docker push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-${{ matrix.arch }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: [lnmp-np-build]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to aliyunHub
        run: docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push Multi-arch Manifest
        run: |
          docker manifest create nuoyis1024/lnmp-np:dev \
            --amend nuoyis1024/lnmp-np:dev-amd64 \
            --amend nuoyis1024/lnmp-np:dev-arm64
          docker manifest push nuoyis1024/lnmp-np:dev
          docker manifest create registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev \
            --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-amd64 \
            --amend registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev-arm64
          docker manifest push registry.cn-hangzhou.aliyuncs.com/nuoyis/lnmp-np:dev