name: Auto Tag and Release

on:
  push:
    branches:
      - main

env:
  REPO: ${{ github.repository }}

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 需要完整历史来获取所有 tag

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "latest_tag=$latest_tag"
          echo "##[set-output name=latest_tag::$latest_tag]"
        shell: bash

      - name: Compute new tag
        id: new_tag
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_latest_tag.outputs.latest_tag }}"
          patch=$((patch + 1))
          new_tag="$major.$minor.$patch"
          echo "new_tag=$new_tag"
          echo "##[set-output name=new_tag::$new_tag]"
        shell: bash

      - name: Create new tag and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git tag ${{ steps.new_tag.outputs.new_tag }}
          git push https://x-access-token:${PAT_TOKEN}@github.com/${REPO} ${{ steps.new_tag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.new_tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}